version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - restore_cache:
          key: promotion-service-deps-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: npm install
      - save_cache:
          key: promotion-service-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build module
          command: npm run build
      - run:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then npm publish --access=public;
            fi
